# Generated by Django 4.2.15 on 2024-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_relieflocation_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='relieflocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
