# Generated by Django 5.1.3 on 2024-12-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_relieflocation_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relieflocation',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
