# Generated by Django 5.1.3 on 2025-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_relieflocation_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
