# Generated by Django 5.1.3 on 2025-01-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
