# Generated by Django 5.1.3 on 2025-01-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.AlterModelOptions(
            name='relieflocation',
            options={'verbose_name': '', 'verbose_name_plural': 'Thông tin'},
        ),
        migrations.AddField(
            model_name='relieflocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian khai báo'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='incident_type',
            field=models.CharField(choices=[('traffic_accident', 'Tai nạn giao thông'), ('drowning', 'Đuối nước'), ('fire', 'Cháy'), ('natural_disaster', 'Thiên tai')], max_length=20, null=True, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='latitude',
            field=models.FloatField(verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='longitude',
            field=models.FloatField(verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi cư trú'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Duyệt'), ('rescued', 'Đã giải quyết')], default='pending', max_length=10, verbose_name='Xử lý thông tin'),
        ),
    ]
