# Generated by Django 5.1.3 on 2025-01-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_delete_incident_alter_relieflocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relieflocation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
    ]
