# Generated by Django 5.1.3 on 2025-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_relieflocation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relieflocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm GPS'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
    ]
