# Generated by Django 4.2.15 on 2024-09-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReliefPoint',
        ),
    ]
